### PR TITLE
Feat: update dependencies

### LINKED ISSUE #18: Bump actix-rt to 2.1.0
As well as support of tokio 1.0

### PR DESCRIPTION
**Pull request by edg-l**
Fixes #18

### CODE REVIEW

**Comment by hackerchai** [comment]
@edg-l  we should wait `actix-casbin-auth` to bump version in order to support tokio 1.0

**Comment by kunjee17** [comment]
Any update on this. `actix-casbin-auth` is already on beta and tokio 1.X ?

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hackerchai** [comment]
> Any update on this. `actix-casbin-auth` is already on beta and tokio 1.X ?

We are still waiting the  actix-web 4.0 release

**Comment by hsluoyz** [comment]
@hackerchai v4.1.0 has been released: https://docs.rs/actix-web/latest/actix_web/ can we continue this PR?

**Comment by hsluoyz** [comment]
@SiddheshKanawade

**Pull request closed without merging**
